version: '3'
services:
  odfe-node1:
    image: singharunk/elasticsearch:7.10.2-plugin-nodemo
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./elastic-certificate.pem:/usr/share/elasticsearch/config/elastic-certificate.pem
      - ./elastic-privatekey.pem:/usr/share/elasticsearch/config/elastic-privatekey.pem
      - ./rootCA.pem:/usr/share/elasticsearch/config/rootCA.pem
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
  odfe-node2:
    image: singharunk/elasticsearch:7.10.2-plugin-nodemo
    container_name: odfe-node2
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./elastic-certificate.pem:/usr/share/elasticsearch/config/elastic-certificate.pem
      - ./elastic-privatekey.pem:/usr/share/elasticsearch/config/elastic-privatekey.pem
      - ./rootCA.pem:/usr/share/elasticsearch/config/rootCA.pem
#      - ./tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
#      - ./roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
#      - ./action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
    networks:
      - odfe-net
  kibana:
    image: singharunk/kibana:7.10.2-plugin
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - odfe-net
    volumes:
      - ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana-certificate.pem:/usr/share/kibana/config/kibana-certificate.pem
      - ./kibana-privatekey.pem:/usr/share/kibana/config/kibana-privatekey.pem
      - ./elastic-certificate.pem:/usr/share/kibana/config/elastic-certificate.pem
      
  logstash:
    image: logstash/logstash:7.10.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./rootCA.pem:/usr/share/logstash/config/rootCA.pem
      - ./lgs-certificate.pem:/usr/share/logstash/config/lgs-certificate.pem
      - ./lgs-privatekey.pem:/usr/share/logstash/config/lgs-privatekey.pem
    ports:
      - "5011:5011"
      - "5044:5044"
    networks:
      - odfe-net
    depends_on:
      - odfe-node1
volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
