# root ca for admin and node certs/keys
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: adminroot
data:
  root-ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtVENDQW9HZ0F3SUJBZ0lVSnBZS1BGdmRKemIwa0NNTkRKM0FuY1VHTjNZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNWVk14RGpBTUJnTlZCQWdNQlVSVlRVMVpNUTR3REFZRFZRUUhEQVZFVlUxTgpXVEVPTUF3R0ExVUVDZ3dGUkZWTlRWa3hEakFNQmdOVkJBc01CVVJWVFUxWk1RMHdDd1lEVlFRRERBUnliMjkwCk1CNFhEVEl4TURjd01qRTFNekExTjFvWERUSXhNRGd3TVRFMU16QTFOMW93WERFTE1Ba0dBMVVFQmhNQ1ZWTXgKRGpBTUJnTlZCQWdNQlVSVlRVMVpNUTR3REFZRFZRUUhEQVZFVlUxTldURU9NQXdHQTFVRUNnd0ZSRlZOVFZreApEakFNQmdOVkJBc01CVVJWVFUxWk1RMHdDd1lEVlFRRERBUnliMjkwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBc1lKZytzdFRyRmZjSUNoLytVYTNBdVhoNWxOQjBHaEdmR0ZMQkdhWWNiaUoKQkxDOCs0M0xBWXRBUlc3aXJJSXMvNnFsdFJVa0diK0xta0pjeC9aNmlBdEttR0dnT20veEJYM0FxakRqaExpMQpCYy9YNktlUDJ5YXNzc3NPTm1jVTB4aTZ0VHhxbHlxWEh2QWpJVWRQbzVGV2dPdWF0RS9XeGNYV0JvYTFNNjRwClE2bTd5SFhhMlRtNE5XZUdad3ZCWENqa3BhckpTdzRmMlpSS2gvT2dqb0twaVl1cDVoZWRpZWNLYXJqZmxuNkUKMnZwaEI0ZHpMak5HVGVUVUF2Y0ZCcWhEdDVyY1JXR09qUnFmUVV0b0RzMUNzeFAvdWE0YVBqMGVOQ2ZkNDl5RApVVHdkSlgrbnhMTEd1RzVtQzUzOXo0MXIxU0lCZzhKUnFsSkZTQ1JhOVFJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVwQ2lrWVd6UWhpVFhBTTlFajV6b2ZDWk9uQWN3SHdZRFZSMGpCQmd3Rm9BVXBDaWtZV3pRaGlUWEFNOUUKajV6b2ZDWk9uQWN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZUNySAprOHZacnNXZWZaTFpWclpTaTVmb1l1TWFYdnhsZ0ZIR3ZWQmFMS1FaZWx6dWV4Vi9NY09hazZQSE1XcHlYUjFzCis3QlZaRWswaG5hQnM2RnI1eGhick5xZG9IQ0JHU2pEMndyTGFVdjN6N2k1VXhyU3kzMmg5U2I0bG9sWDRMMmsKSmF5U2plcDJMYnFjdjhrZzY1cFhKU3o0SnNsRkg5R2ZGUzFJenNSaVFvMHFaUFdLcEx6WmlZQWo2Zk1uekgxZAp6dGFadFIyL1MzMGpudlZwMjdTdVZPQzZZY3IwQjNWMC9CS1dvV2ZnSG10L3B6WG5qRnFmckowcDlVT3RxakpLCmoxWkdYNEJLNStBUFBKbVIzRnZ3OVFtMnZ1d0NwUmRpMzBDZWEwVDFodWI0Y2h2VUpvVHhLYmo4bThReTZzVzgKSmIzTzdESjB0dG03NDZ5Rm93PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: nodekey
data:
  node-key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRQzNIRVV2cmVremJKSVcKRHJ4VDlZVHJ0cDZvR0N6VGlvYndZZUNQdTIya1dwcVQ4b0VIcWtvT0w5VzBHZ1BQcHByRVVkSDFINE5QdlYwZwp1Y3d1WUNPNHpzaGE1c2ErM0x5RERUcCtRV1JqeEo3Z3U1Ukc3K1kyaFh6M3AyY3FlZkduT3R2NGZ6Qi9uMDZXCjFSZmNnWVEvTTlXcHVZV1hhWW5ZSXBhcFFvbURManBVWlQ5YU00cWdzNEVrN3hybUhYMEU5SnpGUStrcHhUdXAKaktzR0hTdjE1UStrTzJUanF4SENpcXZYY2pyU1liVzd0SEN1eEpPRk4xVVhKSkdTaEZ1bGFFUW13ckwvaWNzaQpnNnNHUTBseHIxSm1OL1VSVHBEWmpCOUZNZ1NzMi9kc2hHdlVxdXJjb0NxVzVINjJ6V2ZybWxjOVlQRzVEbnV3ClovMk8wVHluQWdNQkFBRUNnZ0VCQUxKc3hhMzBGS3liT3E1cnBXOWFhaThWUC93anNtcGZMYVhHZWY4VWIzNGIKRzB6V25JeFBqdUhNRXJ6d0xJNkdsWUIvQ2N1RTdYc2gxa0V4U3BoVjdma0M1WkJPRjVPYm04VkhlcHZVTkhKVApBVTJTK3FVMDFtcUNJSWRoZzlHTUNjRWVSWUlhemJOT0ZGSTlTb2IvWFZJSXZFWXFGTmE1YkN4RFovTitkbWh2CldVVnlrbW40UXVwTXN4ZXYzVkw5NE9GcGYwTWtmRWdOY1lmOUpqVUNoMVo1YTJ4MlU3eXc0NVVNUEY0dnBNdDYKUkhHb1ZOZGZBaUNIVWU4cXdWKyttUG1vOUI4REtzL0RGTWdkSUs3VFlFaTNIdWhlSkNXZEdkV1gwZlo4eDhRYgphY3RONEg1dmdTcDRGVGlWcGFRdEluUW1jYzZSTG9YbEFPd1RnUlRwS01FQ2dZRUEyeVE2QU9nelg5WW8weUlxCko4YUc4RThBQnY0ZHlVcUYybW1wOEFobGZYekoyeTB1SzlNK1ZocktiQzA0VjJmTzVOZ1c3dURYUEVFdnh0VjIKMnQ2ZUdZQmE1MjVpZ1RiR3NlVHljWVlXa1A0MUw3eDlYc1piRnU1amlIMWZENERjcERFTGNTTVUwLy9acENhdwp2S1BpMmtIcnYwNExFbXY1eHFudEl2MVUxdThDZ1lFQTFlaWUvRlNkR1ZHWE5xMGROLyttUDUzdy9aSUdsZmZlCjI4QjF6N2M5aW55QXJ1NzBkc1ZrNUFvMUFxeUF5Sk85UXRuSVc5bSszWDlLRTBva2IycXpEalRDUTBYTzJHQisKbEJxL1dyV2lxWDF2OEVob1k2T1Nhd3NUNTlBRjVHRXNSNlRqYy9jNkJIcHhnaWQ4MWtsc29xbmpDVkNidDNsQwphVzUvYTB5Yk5ja0NnWUVBd3k0UjUycnBEd3ZNMHJnVU9kY05xbzJDWmJnQnlaM3hlQ1l5Y0pMWjZobXlJOStxCnh1ZmdGb3JJRGU5OHhnUzBkb2lzYkZpZis0L0h3TjJ4ZmFGWHlUalVQbHJIcTNTaEppTFhlUnRIa0I2S09wazAKUkt5QXh2ek9jK3ZPTmgyODV4U3pyekhpeEN1VnFpbTNzbHg1bVpHcktubVZUUFFVeE1mbWFRcWZmTXNDZ1lFQQpzbm14MVVWZ0FwVUIvdHUzNmxaQ3h3ZW40Rm9yWm90M0JaRnllc29mN2VGdG1RZkZMeWdKd3Y4Rk5lTHFYUEJ2CjFFeFRrTmVBR2QwdjJDSmZmaHJmcFBXK05GVVZmWklkYXNOYWIzdm5hVlZBeFpJVWp6WVdYM3ZSc3ZQdFJwMFIKVGdHMHliZzRUeTQrY09NemxMT1VrYS8vdjNEalM5VS81U29ONUYvNWpJa0NnWUVBcW8yMzQ4UWVlbEdOelZPYgpWWkFpeHp4a1QzY1lFME5JQTB3OGl6SDkyWCtuTjdFYy9qa002QlJxRWI5dHFpZndxY2wwYmxocHYzZVpqUjJqCjlseVlWTkV0b2J3bmszRHFYWmJ2S3ZvSlFlTDNPdG42Y2pOSnFlc3JHN1BNSjdETmpaNmdyUFVmRW8wNG5FemoKa1pjYlhLSjJTSVRLdEpWaXgzMHJXMkZxOHdvPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: nodecert
data:
  node.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUVENDQWpVQ0ZHbFgxNU51Z0VsNWFyMVFzR1RTT20zREhNNkVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Gd3gKQ3pBSkJnTlZCQVlUQWxWVE1RNHdEQVlEVlFRSURBVkVWVTFOV1RFT01Bd0dBMVVFQnd3RlJGVk5UVmt4RGpBTQpCZ05WQkFvTUJVUlZUVTFaTVE0d0RBWURWUVFMREFWRVZVMU5XVEVOTUFzR0ExVUVBd3dFY205dmREQWVGdzB5Ck1UQTNNREl4TlRNME1EaGFGdzB5TVRBNE1ERXhOVE0wTURoYU1Hb3hDekFKQmdOVkJBWVRBbFZUTVE0d0RBWUQKVlFRSURBVkVWVTFOV1RFT01Bd0dBMVVFQnd3RlJGVk5UVmt4RGpBTUJnTlZCQW9NQlVSVlRVMVpNUTR3REFZRApWUVFMREFWRVZVMU5XVEViTUJrR0ExVUVBd3dTWld4aGMzUnBZM05sWVhKamFDMXViMlJsTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHh4Rkw2M3BNMnlTRmc2OFUvV0U2N2FlcUJnczA0cUcKOEdIZ2o3dHRwRnFhay9LQkI2cEtEaS9WdEJvRHo2YWF4RkhSOVIrRFQ3MWRJTG5NTG1BanVNN0lXdWJHdnR5OApndzA2ZmtGa1k4U2U0THVVUnUvbU5vVjg5NmRuS25ueHB6cmIrSDh3ZjU5T2x0VVgzSUdFUHpQVnFibUZsMm1KCjJDS1dxVUtKZ3k0NlZHVS9Xak9Lb0xPQkpPOGE1aDE5QlBTY3hVUHBLY1U3cVl5ckJoMHI5ZVVQcER0azQ2c1IKd29xcjEzSTYwbUcxdTdSd3JzU1RoVGRWRnlTUmtvUmJwV2hFSnNLeS80bkxJb09yQmtOSmNhOVNaamYxRVU2UQoyWXdmUlRJRXJOdjNiSVJyMUtycTNLQXFsdVIrdHMxbjY1cFhQV0R4dVE1N3NHZjlqdEU4cHdJREFRQUJNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFDZWlMOEZaT1hIZkFmV0laL1NjeUFNVVBRZHpNUVZjZmdEcVJQYWd5WUwKNDJQa21yay9tb0F1cTZNTXV4dlRqZUJ1SkNjN2I3bmpmQmxoV2xjWnFsalBZWGYwNDdMeFF6aUxUUjdzdXVEOQpYdzg3MnFtbjl6b0k4MG5ZRjd1UDBwUUs4cUtsWHZkTGZTaXljVS82UGY1aStiM2h5OXM0R3ZwNVhCZG4xMVU0CmRzNzJlY25iQmdtZlpoQ2pFdFBRQk1GQTZ3QlBPM1NJZVFqWFdzSDMxQmhZcE9nbVVaNzVMNGdDUUdxVU9ib1YKYzdjTys3Z1MrM0gzcTdXejVMeDgxTEFkVFE5Y1YyR3dYMmpxZCs1RnpUTXlWNUI5Mk9rQitIcnI2N1pSUjFTWQpNL1ZZcndQUjNKZDdoOVdiTXIyU0dSaU9yc21wMmxnUFREUTdCam1sazR6cwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: privatekey
data:
  elastic-privatekey.pem: <base64 data>
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: admincert
data:
  admin.pem: <base64 data>
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: adminkey
data:
  admin-key.pem: <base64 data>
---
# Elastic and Kibana CA
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: rootca
data:
  rootCA.pem: <base64 data>
---
# Kibana Private Key
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: kibanaprivatekey
data:
  kibana-privatekey.pem: <base64 data>
---
# Kibana Certificate
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: elk-kibana-certificate-pem
  namespace: mykube
data:
  kibana-certificate.pem: <base64 data>
---
# Elastic Certificate
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elk-elasticsearch
    cluster: dev
    env: poc
  name: esnode
data:
  elastic-certificate.pem: <base64 data>
