# Customised Image
ARG IMG_TAG=7.10.2
FROM docker.elastic.co/kibana/kibana:$IMG_TAG
RUN bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/opendistroSecurityKibana-1.13.0.1.zip
